Vagrant.configure("2") do |config|
  config.vm.define "snake04" do |snake04|
    snake04.vm.box = "bento/ubuntu-18.04"
    snake04.vm.hostname = 'snake04'
    snake04.vm.box_url = "bento/ubuntu-18.04"
    
    snake04.vm.network :public_network, ip: "192.168.0.60"

    snake04.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--cpus", 1]
      v.customize ["modifyvm", :id, "--name", "snake04"]
      end
    end

      # Enable provisioning with Ansible.
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/main.yml"
    ansible.playbook = "provisioning/ubuntu_pkg.yml"
    #ansible.playbook = "provisioning/ubuntu_repo.yml"
    #ansible.playbook = "provisioning/ubuntu_python.yml"
    end