- hosts: all:servers
  gather_facts: True
  remote_user: vagrant
  tasks:
  - name: Applying Aliases
    command:
        alias vi='vim'
        alias cp='cp -i'
        alias egrep='egrep --color=auto'
        alias fgrep='fgrep --color=auto'
        alias grep='grep --color=auto'
        alias l.='ls -d .* --color=auto'
        alias ll='ls -l --color=auto'
        alias ls='ls --color=auto'
        alias mv='mv -i'
        alias rm='rm -i'
    become: true
