- hosts: all:servers
  gather_facts: True
  remote_user: vagrant
  tasks:
  - name: Copying Hosts file
    copy: 
      src: /Users/eddiesantos/VirtualBox VMs/Vagrant/provisioning/template/sshd_config
      dest: /etc/ssh/sshd_config
      mode: 0644
      owner: root
      group: root
    become: true
